stages:
  data_preprocessing:
    cmd: python src/data_preprocessing.py
    deps:
      - src/data_preprocessing.py
      - data/raw/dataset.csv
    params:
      - preprocessing.missing_strategy
      - preprocessing.outlier_threshold
    outs:
      - data/processed/clean_dataset.csv

  feature_engineering:
    cmd: python src/feature_engineering.py
    deps:
      - src/feature_engineering.py
      - data/processed/clean_dataset.csv
    params:
      - feature_engineering.scaling_method
      - feature_engineering.feature_selection
    outs:
      - data/features/engineered_features.csv
      - data/features/feature_importance.json

  train_model:
    cmd: python src/train_model.py
    deps:
      - src/train_model.py
      - data/features/engineered_features.csv
    params:
      - model.algorithm
      - model.hyperparameters
    outs:
      - models/model.joblib
      - models/feature_pipeline.joblib
    metrics:
      - metrics/train_metrics.json
    plots:
      - plots/confusion_matrix.json
      - plots/feature_importance.json