preprocessing:
  missing_strategy: 'median'
  outlier_threshold: 3.0
  
feature_engineering:
  scaling_method: 'standard'
  feature_selection: true
  n_features: 20
  
model:
  algorithm: 'random_forest'
  hyperparameters:
    n_estimators: 100
    max_depth: 10
    random_state: 42