name: Feast Materialize

on:
  push:
    branches:
      - main

jobs:
  materialize_features:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: us-east-1
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python and dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip
          pip3 install 'feast[aws]'

      - name: Materialize Feast features
        run: |
          # feast materialize-incremental uses the end time and last 
          cd my_feature_repo
          feast apply # register/update your feature repo definitions 
          # incrementally load feature data from offline to online store within time range
          feast materialize-incremental 2025-08-01T00:00:00 2025-08-27T14:00:00